export interface RepoConfig {
  id: number;
  slug: string;
  name: string;
  localDir: string;
  originalUrl: string;
  resolvedUrl: string;
  substituted: boolean;
  category: string;
  attribution: string;
  fileExtensions: string[];
}

export const REPO_CONFIGS: RepoConfig[] = [
  {
    id: 1,
    slug: "zimbabwe-legislation",
    name: "Zimbabwe Legislation — High Court Act, Magistrates Court Act",
    localDir: "01-zimbabwe-legislation",
    originalUrl: "https://github.com/laws-zm/laws-zimbabwe",
    resolvedUrl: "curated:government-of-zimbabwe/gazette",
    substituted: true,
    category: "Zimbabwe & SADC Legislation",
    attribution: "Government of Zimbabwe, Ministry of Justice; Veritas Zimbabwe (veritas.org.zw)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 2,
    slug: "openlaws-africa",
    name: "Zimbabwe Primary Legislation — Open Legal Text",
    localDir: "02-openlaws-africa",
    originalUrl: "https://github.com/openlaws-africa/zimbabwe-legislation",
    resolvedUrl: "curated:veritas-zimbabwe/primary-legislation",
    substituted: true,
    category: "Zimbabwe & SADC Legislation",
    attribution: "Veritas Zimbabwe (veritas.org.zw); Ministry of Justice, Legal and Parliamentary Affairs",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 3,
    slug: "sadc-legislation",
    name: "SADC Region Legislation — Treaties and Protocols",
    localDir: "03-sadc-legislation",
    originalUrl: "https://github.com/africanlii/sadc-legislation",
    resolvedUrl: "curated:sadc-secretariat/treaties",
    substituted: true,
    category: "Zimbabwe & SADC Legislation",
    attribution: "Southern African Development Community Secretariat (sadc.int)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 4,
    slug: "constitutions",
    name: "Constitution of Zimbabwe 2013 — Full Text",
    localDir: "04-constitutions",
    originalUrl: "https://github.com/constitute-project/constitutions",
    resolvedUrl: "curated:government-of-zimbabwe/constitution-2013",
    substituted: true,
    category: "Zimbabwe & SADC Legislation",
    attribution: "Government of Zimbabwe; Constitution of Zimbabwe 2013, Government Gazette Extraordinary No. 6376 (22 May 2013)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 5,
    slug: "africa-legislation",
    name: "African Law Information — SADC Comparative Legislation",
    localDir: "05-africa-legislation",
    originalUrl: "https://github.com/laws-lawi/africa",
    resolvedUrl: "curated:africanlii/sadc-comparative",
    substituted: true,
    category: "Zimbabwe & SADC Legislation",
    attribution: "Laws.Africa (laws.africa); AfricanLII (africanlii.org)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 6,
    slug: "court-rules",
    name: "Zimbabwe Court Rules — High Court Rules SI 202 of 2021, Supreme Court Rules SI 84 of 2018",
    localDir: "06-court-rules",
    originalUrl: "https://github.com/openjusticeza/court-rules",
    resolvedUrl: "curated:government-of-zimbabwe/court-rules",
    substituted: true,
    category: "Civil Procedure Rules & Court Practice",
    attribution: "Government of Zimbabwe, Chief Justice's Rules Committee; High Court Rules SI 202 of 2021; Supreme Court Rules SI 84 of 2018",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 7,
    slug: "practice-directions",
    name: "Zimbabwe High Court Practice Directions",
    localDir: "07-practice-directions",
    originalUrl: "https://github.com/commonwealth-legal/practice-directions",
    resolvedUrl: "curated:high-court-zimbabwe/practice-directions",
    substituted: true,
    category: "Civil Procedure Rules & Court Practice",
    attribution: "High Court of Zimbabwe (judiciary.org.zw); Chief Justice's Office consolidated practice directions",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 8,
    slug: "sadc-judgments",
    name: "Zimbabwe and Southern African Civil Judgments",
    localDir: "08-sadc-judgments",
    originalUrl: "https://github.com/saflii-archive/judgments-text",
    resolvedUrl: "curated:saflii/zimlii-public-judgments",
    substituted: true,
    category: "Civil Procedure Rules & Court Practice",
    attribution: "Southern African Legal Information Institute (SAFLII — saflii.org); Zimbabwe Legal Information Institute (ZimLII — zimlii.org)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 9,
    slug: "court-forms",
    name: "Zimbabwe High Court Prescribed Forms and Precedents",
    localDir: "09-court-forms",
    originalUrl: "https://github.com/legal-forms/southern-africa",
    resolvedUrl: "curated:high-court-zimbabwe/forms-si-202-2021",
    substituted: true,
    category: "Civil Procedure Rules & Court Practice",
    attribution: "High Court of Zimbabwe; Forms prescribed in High Court Rules SI 202 of 2021; Zimbabwe Law Society standard precedents",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 10,
    slug: "voet-commentary",
    name: "Voet — Commentary on the Pandects (Roman-Dutch Law Foundation)",
    localDir: "10-voet-commentary",
    originalUrl: "https://github.com/roman-dutch-law/voet-commentary",
    resolvedUrl: "curated:public-domain/voet-pandects",
    substituted: true,
    category: "Roman-Dutch Law Foundations",
    attribution: "Public domain (Joannes Voet, 1647-1713); English adaptation from Gane translation",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 11,
    slug: "grotius-introduction",
    name: "Grotius — Introduction to Dutch Jurisprudence",
    localDir: "11-grotius-introduction",
    originalUrl: "https://github.com/roman-dutch-law/grotius-introduction",
    resolvedUrl: "curated:public-domain/grotius-inleidinge",
    substituted: true,
    category: "Roman-Dutch Law Foundations",
    attribution: "Public domain (Hugo Grotius, 1583-1645); English adaptation from R.W. Lee translation",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 12,
    slug: "roman-dutch-texts",
    name: "Van der Linden — Institutes of Holland (Public Domain)",
    localDir: "12-roman-dutch-texts",
    originalUrl: "https://github.com/openlibrary-law/south-african-law-texts",
    resolvedUrl: "curated:public-domain/van-der-linden-institutes",
    substituted: true,
    category: "Roman-Dutch Law Foundations",
    attribution: "Public domain (Joannes van der Linden, 1756-1835); English adaptation from Henry Juta translation (1884)",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 13,
    slug: "legal-english",
    name: "Legal English Style Guide — Zimbabwe Superior Courts",
    localDir: "13-legal-english",
    originalUrl: "https://github.com/plain-language/legal-english",
    resolvedUrl: "curated:original/lex-superior-style-guide",
    substituted: true,
    category: "Legal English Language, Drafting & Style",
    attribution: "Original compilation for Lex Superior knowledge base; Zimbabwe Law Society CPD materials",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 14,
    slug: "legal-language-corpus",
    name: "Legal Language Clarity — Drafting Resources",
    localDir: "14-legal-language-corpus",
    originalUrl: "https://github.com/legal-design-lab/legal-language-corpus",
    resolvedUrl: "curated:original/lex-superior-language-corpus",
    substituted: true,
    category: "Legal English Language, Drafting & Style",
    attribution: "Original compilation; Clarity International Association; Commonwealth Law Reform Commission principles",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 15,
    slug: "legal-lexicon",
    name: "Zimbabwe Legal Dictionary — Terms of Art and Glossary",
    localDir: "15-legal-lexicon",
    originalUrl: "https://github.com/wordlaw/legal-lexicon",
    resolvedUrl: "curated:original/lex-superior-lexicon",
    substituted: true,
    category: "Legal English Language, Drafting & Style",
    attribution: "Original compilation; Stroud's Judicial Dictionary (public domain extracts); Zimbabwe case law",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 16,
    slug: "advocacy-guides",
    name: "Formal Legal Writing and Advocacy — Zimbabwe Superior Courts",
    localDir: "16-advocacy-guides",
    originalUrl: "https://github.com/openlegalwriting/advocacy-guides",
    resolvedUrl: "curated:original/lex-superior-advocacy",
    substituted: true,
    category: "Legal English Language, Drafting & Style",
    attribution: "Original compilation; Zimbabwe Law Society CPD materials; published legal texts",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 17,
    slug: "legal-latin",
    name: "Legal Latin Maxims — Comprehensive Glossary",
    localDir: "17-legal-latin",
    originalUrl: "https://github.com/law-commons/legal-latin",
    resolvedUrl: "curated:original/lex-superior-latin",
    substituted: true,
    category: "Legal English Language, Drafting & Style",
    attribution: "Original compilation; Osborn's Concise Law Dictionary (public domain extracts); Zimbabwe Superior Court judgments",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 18,
    slug: "constitutional-jurisprudence",
    name: "Zimbabwe Constitutional Jurisprudence — Rights Case Summaries",
    localDir: "18-constitutional-jurisprudence",
    originalUrl: "https://github.com/zimrights/constitutional-jurisprudence",
    resolvedUrl: "curated:zimlii/constitutional-court-decisions",
    substituted: true,
    category: "Constitutional & Human Rights Law (Zimbabwe)",
    attribution: "Constitutional Court of Zimbabwe; ZimLII (zimlii.org) public access decisions",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 19,
    slug: "human-rights-corpus",
    name: "Southern Africa Human Rights — Civil and Procedural Dimensions",
    localDir: "19-human-rights-corpus",
    originalUrl: "https://github.com/hrw-legal/africa-rights-corpus",
    resolvedUrl: "curated:un-au/human-rights-treaties",
    substituted: true,
    category: "Constitutional & Human Rights Law (Zimbabwe)",
    attribution: "African Union (African Charter); United Nations Treaty Collection (ICCPR); Zimbabwe Human Rights Commission",
    fileExtensions: [".md", ".txt"],
  },
  {
    id: 20,
    slug: "conveyancing",
    name: "Zimbabwe Conveyancing Procedure — Deeds Registries Act",
    localDir: "20-conveyancing",
    originalUrl: "https://github.com/open-conveyancing/southern-africa",
    resolvedUrl: "curated:government-of-zimbabwe/deeds-registries-act",
    substituted: true,
    category: "Commercial & Property Law Procedure",
    attribution: "Government of Zimbabwe; Deeds Registries Act [Chapter 20:05]; Deeds Registries Regulations SI 76 of 2025; Zimbabwe Law Society conveyancing practice notes",
    fileExtensions: [".md", ".txt"],
  },
];

export const KNOWLEDGE_BASE_DIR = "knowledge/repos";
